[tool.poetry]
name = "weban"
version = "0.4.0"
description = "Free check sites for SEO suitability"
authors = ["Andrey Bogatyrev <donoriono@gmail.com>"]
readme = "README.md"
homepage = "https://weban.2-way.ru"
packages = [{include = "page_analyzer"}]
classifiers = ["License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 3",
               "Environment :: Web",
               "Framework :: flask :: 2.3.2",
               "Operating System :: POSIX :: Linux"]
repository = "https://github.com/Onoiro/weban"


[tool.poetry.scripts]
page-analyzer = "page_analyzer.app:app"


[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.2"
gunicorn = "^23.0"
psycopg2-binary = "^2.9.6"
python-dotenv = "^1.0.0"
validators = "^0.35.0"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
pytest = "^9.0"
pytest-flask = "^1.2.0"
pytest-mock = "^3.11.0"
responses = "^0.25"
pytest-cov = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
