sonar.projectKey=Onoiro_weban
sonar.organization=abo

sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.sources=page_analyzer
sonar.tests=tests

sonar.exclusions=tests/**/*,**/__pycache__/**,**/migrations/**
sonar.coverage.exclusions=tests/**,**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
